project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true

files:
  - source: /Translations for LifeMC/assets/minecraft/lang/en_us.json
    translation: /%original_path%/%locale_with_underscore%.json
